<?php
declare(strict_types = 1);
$view = \Dashboard\Infrastructure\View::getInstance();
?>
<?php if (false !== $view->get('_phpunit', false)): ?>
<a href="#" data-toggle="collapse" data-target="#phpunit_userMenu">
    <i class="fa fa-cubes"></i> PHPUnit <i class="glyphicon glyphicon-chevron-down"></i>
    <div class="pull-right">
        <?php if ($view->get('phpunitData_total_summary_errors_#', 0)): ?>&nbsp;<span class="label label-danger"><?= $view->get('phpunitData_total_summary_errors_#') ?></span><?php endif;?>
        <?php if ($view->get('phpunitData_total_summary_failures_#', 0)): ?>&nbsp;<span class="label label-warning"><?= $view->get('phpunitData_total_summary_failures_#') ?></span><?php endif;?>
        <?php if ($view->get('phpunitData_total_summary_skipped_#', 0)): ?>&nbsp;<span class="label label-info"><?= $view->get('phpunitData_total_summary_skipped_#') ?></span><?php endif;?>
        <?php if ($view->get('phpunitData_total_summary_is_success', false)): ?>&nbsp;<span class="label label-success">OK</span><?php endif;?>
    </div>
</a>
<ul class="nav nav-stacked collapse" id="phpunit_userMenu">
    <?php if ($view->get('phpunitData_unit_exists', false)): ?>
    <li>
        <a href="#phpunit_unit" data-toggle="tab">
            <i class="glyphicon glyphicon-tag"></i> Unit
            <div class="pull-right">
                <?php if ($view->get('phpunitData_unit_summary_errors_#', 0)): ?>&nbsp;<span class="label label-danger"><?= $view->get('phpunitData_unit_summary_errors_#') ?></span><?php endif;?>
                <?php if ($view->get('phpunitData_unit_summary_failures_#', 0)): ?>&nbsp;<span class="label label-warning"><?= $view->get('phpunitData_unit_summary_failures_#') ?></span><?php endif;?>
                <?php if ($view->get('phpunitData_unit_summary_skipped_#', 0)): ?>&nbsp;<span class="label label-info"><?= $view->get('phpunitData_unit_summary_skipped_#') ?></span><?php endif;?>
                <?php if ($view->get('phpunitData_unit_summary_is_success', false)): ?>&nbsp;<span class="label label-success">OK</span><?php endif;?>
            </div>
        </a>
    </li>
    <?php endif; ?>
    <?php if ($view->get('phpunitData_coverage_unit_exists', false)): ?>
    <li>
        <a target="_blank" href="phpunit/coverage-html/index.html">
            <i class="glyphicon glyphicon-zoom-in"></i> Unit Coverage
            <div class="pull-right">
                <?php if ($view->get('phpunitData_coverage_unit_global_%', 0)): ?>&nbsp;<span class="label label-<?= $view->get('phpunitData_coverage_unit_global_badge', 'info');?>"><?= $view->get('phpunitData_coverage_unit_global_%') ?> %</span><?php endif;?>
                <i class="glyphicon glyphicon-new-window"></i>
            </div>
        </a>
    </li>
    <?php endif; ?>
</ul>
<?php endif; ?>

