<?php
declare(strict_types = 1);
$view = \Dashboard\Infrastructure\View::getInstance();
?>
<div class="tab-pane active" id="home">
    <div class="row hidden-xs hidden-sm">
        <div class="col-md-3"><?= $view->import('blocks/tools/phpmetrics/lcom.phtml'); ?></div>
        <div class="col-md-3"><?= $view->import('blocks/tools/phpmetrics/maintainabilityIndex.phtml'); ?></div>
        <div class="col-md-3"><?= $view->import('blocks/tools/phpmetrics/bugs.phtml'); ?></div>
        <div class="col-md-3"><?= $view->import('blocks/tools/phpmetrics/volume.phtml'); ?></div>
    </div>
    <div class="row">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-4">
                    <?= $view->import('blocks/tools/phpmetrics/bubbleChart.phtml'); ?>
                    <?= $view->import('blocks/tools/phpcpd/summary.phtml'); ?>
                </div>
                <div class="col-sm-8">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-sm-<?= $view->get('newmanData_exists', false) ? 6 : 12 ?> <?= $view->get('newmanData_exists', false) ? 'odd' : 'full' ?>">
                                <?php if ($view->get('phpunitData_unit_exists', false)): echo $view->import('blocks/tools/phpunit/all-panels.phtml'); endif; ?>
                            </div>
                            <?php if ($view->get('newmanData_exists', false)): ?>
                            <div class="col-sm-6 even">
                                 <?= $view->import('blocks/tools/newman/summary.phtml'); ?>
                            </div>
                            <?php endif; ?>
                            <?php if ($view->get('phpstanData', false)): ?>
                            <div class="col-sm-6 odd">
                                <?= $view->import('blocks/tools/phpstan/summary.phtml'); ?>
                            </div>
                            <?php endif; ?>
                            <div class="col-sm-<?= $view->get('phpstanData', false) ? 6 : 12 ?> <?= $view->get('phpstanData', false) ? 'even' : 'full' ?>">
                                <?= $view->import('blocks/tools/pdepend/summary-pyramid.phtml'); ?>
                            </div>
                        </div>
                        <div class="row"><?= $view->import('blocks/tools/phpmetrics/locStatistics.phtml'); ?></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
