<?php
declare(strict_types = 1);
$view = \Dashboard\Infrastructure\View::getInstance();
?>
<div class="tab-pane active" id="home">
    <div class="row hidden-xs hidden-sm">
        <div class="col-md-3"><?= $view->import('blocks/tools/phpmetrics/lcom.phtml'); ?></div>
        <div class="col-md-3"><?= $view->import('blocks/tools/phpmetrics/maintainabilityIndex.phtml'); ?></div>
        <div class="col-md-3"><?= $view->import('blocks/tools/phpmetrics/bugs.phtml'); ?></div>
        <div class="col-md-3"><?= $view->import('blocks/tools/phpmetrics/volume.phtml'); ?></div>
    </div>
    <div class="row">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-4">
                    <?= $view->import('blocks/tools/phpmetrics/bubbleChart.phtml'); ?>
                    <?= $view->import('blocks/tools/phpcpd/summary.phtml'); ?>
                </div>
                <div class="col-sm-8">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-sm-12">
                                <?= $view->import('blocks/tools/phpunit/all-panels.phtml'); ?>
                            </div>
                            <div class="col-sm-6">
                                <?= $view->import('blocks/tools/phpmetrics/numberOfStructures.phtml'); ?>
                                <?= $view->import('blocks/tools/phpcs/summary.phtml'); ?>
                            </div>
                            <div class="col-sm-6"><?= $view->import('blocks/tools/pdepend/summary-pyramid.phtml'); ?></div>
                        </div>
                        <div class="row"><?= $view->import('blocks/tools/phpmetrics/locStatistics.phtml'); ?></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>