<?php
declare(strict_types = 1);
$view = \Dashboard\Infrastructure\View::getInstance();
?>
<div class="tab-pane" id="pdepend">
    <div class="container-fluid">
    <?= $view->import('blocks/tools/pdepend/report.phtml'); ?>
    </div>
</div>
<div class="tab-pane" id="pdepend_graphs">
    <div class="container-fluid">
        <?= $view->import('blocks/tools/pdepend/graphs/report.phtml'); ?>
    </div>
</div>