<?php
declare(strict_types = 1);
$view = \Dashboard\Infrastructure\View::getInstance();
?>
<div class="panel panel-<?= $view->get('phpMetricsData_bugs_status', 'info')?>">
    <div class="panel-heading">
        <h4 class="panel-title">Average Bugs probability
            <span class="glyphicon glyphicon-question-sign"
                  data-toggle="tooltip"
                  title="The bugs probability represents the average statistics of the project to have bugs."></span>
        </h4>
    </div>
    <div class="panel-body">
        <div class="text-center" style="font-size:x-large"><?= $view->get('phpMetricsData_bugs_#', 'N/A')?></div>
        <div class="text-center">Must be <strong>the closest to 0</strong>.</div>
    </div>
</div>