<?php
declare(strict_types = 1);
$view = \Dashboard\Infrastructure\View::getInstance();
?>
<div class="panel panel-<?= $view->get('phpMetricsData_lcom_status', 'info')?>">
    <div class="panel-heading">
        <h4 class="panel-title">Average LCOM4
            <span class="glyphicon glyphicon-question-sign"
                  data-toggle="tooltip"
                  title="The LCOM4 represents the complexity of the project."></span>
        </h4>
    </div>
    <div class="panel-body">
        <div class="text-center" style="font-size:x-large"><?= $view->get('phpMetricsData_lcom_#', 'N/A')?></div>
        <div class="text-center">Must stay <strong>between 0 and 1</strong>.</div>
    </div>
</div>