<?php
declare(strict_types = 1);
$view = \Dashboard\Infrastructure\View::getInstance();
?>
<div class="panel panel-<?= $view->get('phpMetricsData_mi_status', 'info')?>">
    <div class="panel-heading">
        <h4 class="panel-title">Average Maintainability Index
            <span class="glyphicon glyphicon-question-sign"
                  data-toggle="tooltip"
                  title="The Maintainability Index represents the maintainability of the project."></span>
        </h4>
    </div>
    <div class="panel-body">
        <div class="text-center" style="font-size:x-large"><?= $view->get('phpMetricsData_mi_#', 'N/A')?></div>
        <div class="text-center">Must be <strong>over 85</strong>.</div>
    </div>
</div>