<?php
declare(strict_types = 1);
$service = \Dashboard\Infrastructure\Parameters::get('service');
$buildDate = \Dashboard\Infrastructure\View::getInstance()->get('DashboardBuildDate_human');
?>
<div id="top-nav" class="navbar navbar-inverse navbar-static-top hidden-xs hidden-sm">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Dashboard - <?= $service; ?> - <?= $buildDate ?></a>
        </div>
    </div>
</div>