<?php
declare(strict_types = 1);
$view = \Dashboard\Infrastructure\View::getInstance();
$summaryErrorNumber = $view->get('phpstan_nbErrors_byLevel_#', []);
$summaryErrorPercent = $view->get('phpstan_nbErrors_byLevel_%', []);
$summaryColors = $view->get('phpstan_colors_summary', []);
?>
<div class="panel panel-primary">
    <div class="panel-heading"><h4 class="panel-title">PHP Stan</h4></div>
    <div class="panel-body" style="min-height: 239px">
        <div class="row">
            <div class="col-sm-12 text-center">
                <p><strong>PHPStan found <?= $view->get('phpstan_nbErrors_#', '0') ?> errors.</strong></p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12" id="phpstanGraph_summary">
                <?php for ($level=\count($summaryErrorNumber)-1; $level>=0; --$level): ?>
                <div class="row">
                    <div class="col-sm-2" style="text-align: right"><strong>Level <?= $level ?></strong></div>
                    <div class="col-sm-10">
                        <div class="progress progress-stack">
                            <div class="progress-bar"
                                 style="background-color: <?= $summaryColors[$level] ?>;width: <?= $summaryErrorPercent[$level] ?>%">
                                <span><?= $summaryErrorNumber[$level] ?></span>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endfor; ?>
            </div>
        </div>
    </div>
</div>